// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import angleRightSolidString from './angleRightSolidString.js';

export default new Shape( angleRightSolidString ).makeImmutable();