// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import arrowAltCircleLeftRegularString from './arrowAltCircleLeftRegularString.js';

export default new Shape( arrowAltCircleLeftRegularString ).makeImmutable();