// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import arrowLeftSolidString from './arrowLeftSolidString.js';

export default new Shape( arrowLeftSolidString ).makeImmutable();