// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import briefcaseSolidString from './briefcaseSolidString.js';

export default new Shape( briefcaseSolidString ).makeImmutable();