// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import bullseyeSolidString from './bullseyeSolidString.js';

export default new Shape( bullseyeSolidString ).makeImmutable();