// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import cartPlusSolidString from './cartPlusSolidString.js';

export default new Shape( cartPlusSolidString ).makeImmutable();