// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import chessPawnSolidString from './chessPawnSolidString.js';

export default new Shape( chessPawnSolidString ).makeImmutable();