// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import commentDotsRegularString from './commentDotsRegularString.js';

export default new Shape( commentDotsRegularString ).makeImmutable();