// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import conciergeBellSolidString from './conciergeBellSolidString.js';

export default new Shape( conciergeBellSolidString ).makeImmutable();