// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import diceD6SolidString from './diceD6SolidString.js';

export default new Shape( diceD6SolidString ).makeImmutable();