// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import featherAltSolidString from './featherAltSolidString.js';

export default new Shape( featherAltSolidString ).makeImmutable();