// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import grinSquintTearsRegularString from './grinSquintTearsRegularString.js';

export default new Shape( grinSquintTearsRegularString ).makeImmutable();