// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import handPointLeftSolidString from './handPointLeftSolidString.js';

export default new Shape( handPointLeftSolidString ).makeImmutable();