// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import paperPlaneRegularString from './paperPlaneRegularString.js';

export default new Shape( paperPlaneRegularString ).makeImmutable();