// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import Shape from '../../../kite/js/Shape.js';
import questionCircleRegularString from './questionCircleRegularString.js';

export default new Shape( questionCircleRegularString );