// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import Shape from '../../../kite/js/Shape.js';
import smileBeamRegularString from './smileBeamRegularString.js';

export default new Shape( smileBeamRegularString );