// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import sortAlphaDownSolidString from './sortAlphaDownSolidString.js';

export default new Shape( sortAlphaDownSolidString ).makeImmutable();