// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import Shape from '../../../kite/js/Shape.js';
import sortAlphaUpAltSolidString from './sortAlphaUpAltSolidString.js';

export default new Shape( sortAlphaUpAltSolidString );