// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import Shape from '../../../kite/js/Shape.js';
import sunSolidString from './sunSolidString.js';

export default new Shape( sunSolidString ).makeImmutable();