// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import trafficLightSolidString from './trafficLightSolidString.js';

export default new Shape( trafficLightSolidString ).makeImmutable();