// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import truckMonsterSolidString from './truckMonsterSolidString.js';

export default new Shape( truckMonsterSolidString ).makeImmutable();