// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import truckPickupSolidString from './truckPickupSolidString.js';

export default new Shape( truckPickupSolidString ).makeImmutable();