// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import Shape from '../../../kite/js/Shape.js';
import userAstronautSolidString from './userAstronautSolidString.js';

export default new Shape( userAstronautSolidString );