// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../kite/js/imports.js';
import vestPatchesSolidString from './vestPatchesSolidString.js';

export default new Shape( vestPatchesSolidString ).makeImmutable();