// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class WindowMaximize extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( WindowMaximize.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
WindowMaximize.PATH_DATA = 'M464 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm0 394c0 3.3-2.7 6-6 6H54c-3.3 0-6-2.7-6-6V192h416v234z';
WindowMaximize.SHAPE = new Shape( WindowMaximize.PATH_DATA );

export default WindowMaximize;