// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class WindowMinimize extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( WindowMinimize.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
WindowMinimize.PATH_DATA = 'M480 480H32c-17.7 0-32-14.3-32-32s14.3-32 32-32h448c17.7 0 32 14.3 32 32s-14.3 32-32 32z';
WindowMinimize.SHAPE = new Shape( WindowMinimize.PATH_DATA );

export default WindowMinimize;