// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class WindowRestore extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( WindowRestore.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
WindowRestore.PATH_DATA = 'M464 0H144c-26.5 0-48 21.5-48 48v48H48c-26.5 0-48 21.5-48 48v320c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h48c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zm-96 464H48V256h320v208zm96-96h-48V144c0-26.5-21.5-48-48-48H144V48h320v320z';
WindowRestore.SHAPE = new Shape( WindowRestore.PATH_DATA );

export default WindowRestore;