// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class AngleLeft extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( AngleLeft.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
AngleLeft.PATH_DATA = 'M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z';
AngleLeft.SHAPE = new Shape( AngleLeft.PATH_DATA );

export default AngleLeft;