// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class ArrowAltCircleDown extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( ArrowAltCircleDown.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
ArrowAltCircleDown.PATH_DATA = 'M504 256c0 137-111 248-248 248S8 393 8 256 119 8 256 8s248 111 248 248zM212 140v116h-70.9c-10.7 0-16.1 13-8.5 20.5l114.9 114.3c4.7 4.7 12.2 4.7 16.9 0l114.9-114.3c7.6-7.6 2.2-20.5-8.5-20.5H300V140c0-6.6-5.4-12-12-12h-64c-6.6 0-12 5.4-12 12z';
ArrowAltCircleDown.SHAPE = new Shape( ArrowAltCircleDown.PATH_DATA );

export default ArrowAltCircleDown;