// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class BatteryHalf extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( BatteryHalf.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
BatteryHalf.PATH_DATA = 'M544 160v64h32v64h-32v64H64V160h480m16-64H48c-26.51 0-48 21.49-48 48v224c0 26.51 21.49 48 48 48h512c26.51 0 48-21.49 48-48v-16h8c13.255 0 24-10.745 24-24V184c0-13.255-10.745-24-24-24h-8v-16c0-26.51-21.49-48-48-48zm-240 96H96v128h224V192z';
BatteryHalf.SHAPE = new Shape( BatteryHalf.PATH_DATA );

export default BatteryHalf;