// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Bookmark extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Bookmark.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Bookmark.PATH_DATA = 'M0 512V48C0 21.49 21.49 0 48 0h288c26.51 0 48 21.49 48 48v464L192 400 0 512z';
Bookmark.SHAPE = new Shape( Bookmark.PATH_DATA );

export default Bookmark;