// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class BreadSlice extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( BreadSlice.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
BreadSlice.PATH_DATA = 'M288 0C108 0 0 93.4 0 169.14 0 199.44 24.24 224 64 224v256c0 17.67 16.12 32 36 32h376c19.88 0 36-14.33 36-32V224c39.76 0 64-24.56 64-54.86C576 93.4 468 0 288 0z';
BreadSlice.SHAPE = new Shape( BreadSlice.PATH_DATA );

export default BreadSlice;