// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class CaretRight extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( CaretRight.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
CaretRight.PATH_DATA = 'M0 384.662V127.338c0-17.818 21.543-26.741 34.142-14.142l128.662 128.662c7.81 7.81 7.81 20.474 0 28.284L34.142 398.804C21.543 411.404 0 402.48 0 384.662z';
CaretRight.SHAPE = new Shape( CaretRight.PATH_DATA );

export default CaretRight;