// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class CaretSquareLeft extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( CaretSquareLeft.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
CaretSquareLeft.PATH_DATA = 'M400 480H48c-26.51 0-48-21.49-48-48V80c0-26.51 21.49-48 48-48h352c26.51 0 48 21.49 48 48v352c0 26.51-21.49 48-48 48zM259.515 124.485l-123.03 123.03c-4.686 4.686-4.686 12.284 0 16.971l123.029 123.029c7.56 7.56 20.485 2.206 20.485-8.485V132.971c.001-10.691-12.925-16.045-20.484-8.486z';
CaretSquareLeft.SHAPE = new Shape( CaretSquareLeft.PATH_DATA );

export default CaretSquareLeft;