// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class CaretDown extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( CaretDown.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
CaretDown.PATH_DATA = 'M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z';
CaretDown.SHAPE = new Shape( CaretDown.PATH_DATA );

export default CaretDown;