// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Chalkboard extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Chalkboard.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Chalkboard.PATH_DATA = 'M96 64h448v352h64V40c0-22.06-17.94-40-40-40H72C49.94 0 32 17.94 32 40v376h64V64zm528 384H480v-64H288v64H16c-8.84 0-16 7.16-16 16v32c0 8.84 7.16 16 16 16h608c8.84 0 16-7.16 16-16v-32c0-8.84-7.16-16-16-16z';
Chalkboard.SHAPE = new Shape( Chalkboard.PATH_DATA );

export default Chalkboard;