// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Cheese extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Cheese.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Cheese.PATH_DATA = 'M0 288v160a32 32 0 0 0 32 32h448a32 32 0 0 0 32-32V288zM299.83 32a32 32 0 0 0-21.13 7L0 256h512c0-119.89-94-217.8-212.17-224z';
Cheese.SHAPE = new Shape( Cheese.PATH_DATA );

export default Cheese;