// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class ChevronCircleRight extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( ChevronCircleRight.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
ChevronCircleRight.PATH_DATA = 'M256 8c137 0 248 111 248 248S393 504 256 504 8 393 8 256 119 8 256 8zm113.9 231L234.4 103.5c-9.4-9.4-24.6-9.4-33.9 0l-17 17c-9.4 9.4-9.4 24.6 0 33.9L285.1 256 183.5 357.6c-9.4 9.4-9.4 24.6 0 33.9l17 17c9.4 9.4 24.6 9.4 33.9 0L369.9 273c9.4-9.4 9.4-24.6 0-34z';
ChevronCircleRight.SHAPE = new Shape( ChevronCircleRight.PATH_DATA );

export default ChevronCircleRight;