// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class ChevronCircleUp extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( ChevronCircleUp.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
ChevronCircleUp.PATH_DATA = 'M8 256C8 119 119 8 256 8s248 111 248 248-111 248-248 248S8 393 8 256zm231-113.9L103.5 277.6c-9.4 9.4-9.4 24.6 0 33.9l17 17c9.4 9.4 24.6 9.4 33.9 0L256 226.9l101.6 101.6c9.4 9.4 24.6 9.4 33.9 0l17-17c9.4-9.4 9.4-24.6 0-33.9L273 142.1c-9.4-9.4-24.6-9.4-34 0z';
ChevronCircleUp.SHAPE = new Shape( ChevronCircleUp.PATH_DATA );

export default ChevronCircleUp;