// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class ChevronCircleDown extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( ChevronCircleDown.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
ChevronCircleDown.PATH_DATA = 'M504 256c0 137-111 248-248 248S8 393 8 256 119 8 256 8s248 111 248 248zM273 369.9l135.5-135.5c9.4-9.4 9.4-24.6 0-33.9l-17-17c-9.4-9.4-24.6-9.4-33.9 0L256 285.1 154.4 183.5c-9.4-9.4-24.6-9.4-33.9 0l-17 17c-9.4 9.4-9.4 24.6 0 33.9L239 369.9c9.4 9.4 24.6 9.4 34 0z';
ChevronCircleDown.SHAPE = new Shape( ChevronCircleDown.PATH_DATA );

export default ChevronCircleDown;