// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class EllipsisH extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( EllipsisH.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
EllipsisH.PATH_DATA = 'M328 256c0 39.8-32.2 72-72 72s-72-32.2-72-72 32.2-72 72-72 72 32.2 72 72zm104-72c-39.8 0-72 32.2-72 72s32.2 72 72 72 72-32.2 72-72-32.2-72-72-72zm-352 0c-39.8 0-72 32.2-72 72s32.2 72 72 72 72-32.2 72-72-32.2-72-72-72z';
EllipsisH.SHAPE = new Shape( EllipsisH.PATH_DATA );

export default EllipsisH;