// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class EllipsisV extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( EllipsisV.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
EllipsisV.PATH_DATA = 'M96 184c39.8 0 72 32.2 72 72s-32.2 72-72 72-72-32.2-72-72 32.2-72 72-72zM24 80c0 39.8 32.2 72 72 72s72-32.2 72-72S135.8 8 96 8 24 40.2 24 80zm0 352c0 39.8 32.2 72 72 72s72-32.2 72-72-32.2-72-72-72-72 32.2-72 72z';
EllipsisV.SHAPE = new Shape( EllipsisV.PATH_DATA );

export default EllipsisV;