// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class FastBackward extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( FastBackward.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
FastBackward.PATH_DATA = 'M0 436V76c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v151.9L235.5 71.4C256.1 54.3 288 68.6 288 96v131.9L459.5 71.4C480.1 54.3 512 68.6 512 96v320c0 27.4-31.9 41.7-52.5 24.6L288 285.3V416c0 27.4-31.9 41.7-52.5 24.6L64 285.3V436c0 6.6-5.4 12-12 12H12c-6.6 0-12-5.4-12-12z';
FastBackward.SHAPE = new Shape( FastBackward.PATH_DATA );

export default FastBackward;