// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class FolderMinus extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( FolderMinus.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
FolderMinus.PATH_DATA = 'M464 128H272l-64-64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V176c0-26.51-21.49-48-48-48zm-96 168c0 8.84-7.16 16-16 16H160c-8.84 0-16-7.16-16-16v-16c0-8.84 7.16-16 16-16h192c8.84 0 16 7.16 16 16v16z';
FolderMinus.SHAPE = new Shape( FolderMinus.PATH_DATA );

export default FolderMinus;