// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Genderless extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Genderless.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Genderless.PATH_DATA = 'M144 176c44.1 0 80 35.9 80 80s-35.9 80-80 80-80-35.9-80-80 35.9-80 80-80m0-64C64.5 112 0 176.5 0 256s64.5 144 144 144 144-64.5 144-144-64.5-144-144-144z';
Genderless.SHAPE = new Shape( Genderless.PATH_DATA );

export default Genderless;