// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class GlassMartini extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( GlassMartini.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
GlassMartini.PATH_DATA = 'M502.05 57.6C523.3 36.34 508.25 0 478.2 0H33.8C3.75 0-11.3 36.34 9.95 57.6L224 271.64V464h-56c-22.09 0-40 17.91-40 40 0 4.42 3.58 8 8 8h240c4.42 0 8-3.58 8-8 0-22.09-17.91-40-40-40h-56V271.64L502.05 57.6z';
GlassMartini.SHAPE = new Shape( GlassMartini.PATH_DATA );

export default GlassMartini;