// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class GripLines extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( GripLines.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
GripLines.PATH_DATA = 'M496 288H16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h480c8.8 0 16-7.2 16-16v-32c0-8.8-7.2-16-16-16zm0-128H16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h480c8.8 0 16-7.2 16-16v-32c0-8.8-7.2-16-16-16z';
GripLines.SHAPE = new Shape( GripLines.PATH_DATA );

export default GripLines;