// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class GripLinesVertical extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( GripLinesVertical.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
GripLinesVertical.PATH_DATA = 'M96 496V16c0-8.8-7.2-16-16-16H48c-8.8 0-16 7.2-16 16v480c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16zm128 0V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v480c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16z';
GripLinesVertical.SHAPE = new Shape( GripLinesVertical.PATH_DATA );

export default GripLinesVertical;