// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class HockeyPuck extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( HockeyPuck.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
HockeyPuck.PATH_DATA = 'M0 160c0-53 114.6-96 256-96s256 43 256 96-114.6 96-256 96S0 213 0 160zm0 82.2V352c0 53 114.6 96 256 96s256-43 256-96V242.2c-113.4 82.3-398.5 82.4-512 0z';
HockeyPuck.SHAPE = new Shape( HockeyPuck.PATH_DATA );

export default HockeyPuck;