// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class IceCream extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( IceCream.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
IceCream.PATH_DATA = 'M368 160h-.94a144 144 0 1 0-286.12 0H80a48 48 0 0 0 0 96h288a48 48 0 0 0 0-96zM195.38 493.69a31.52 31.52 0 0 0 57.24 0L352 288H96z';
IceCream.SHAPE = new Shape( IceCream.PATH_DATA );

export default IceCream;