// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class LocationArrow extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( LocationArrow.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
LocationArrow.PATH_DATA = 'M444.52 3.52L28.74 195.42c-47.97 22.39-31.98 92.75 19.19 92.75h175.91v175.91c0 51.17 70.36 67.17 92.75 19.19l191.9-415.78c15.99-38.39-25.59-79.97-63.97-63.97z';
LocationArrow.SHAPE = new Shape( LocationArrow.PATH_DATA );

export default LocationArrow;