// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class LongArrowAltUp extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( LongArrowAltUp.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
LongArrowAltUp.PATH_DATA = 'M88 166.059V468c0 6.627 5.373 12 12 12h56c6.627 0 12-5.373 12-12V166.059h46.059c21.382 0 32.09-25.851 16.971-40.971l-86.059-86.059c-9.373-9.373-24.569-9.373-33.941 0l-86.059 86.059c-15.119 15.119-4.411 40.971 16.971 40.971H88z';
LongArrowAltUp.SHAPE = new Shape( LongArrowAltUp.PATH_DATA );

export default LongArrowAltUp;