// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class LongArrowAltLeft extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( LongArrowAltLeft.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
LongArrowAltLeft.PATH_DATA = 'M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z';
LongArrowAltLeft.SHAPE = new Shape( LongArrowAltLeft.PATH_DATA );

export default LongArrowAltLeft;