// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class MinusSquare extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( MinusSquare.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
MinusSquare.PATH_DATA = 'M400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zM92 296c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h264c6.6 0 12 5.4 12 12v56c0 6.6-5.4 12-12 12H92z';
MinusSquare.SHAPE = new Shape( MinusSquare.PATH_DATA );

export default MinusSquare;