// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class MinusCircle extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( MinusCircle.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
MinusCircle.PATH_DATA = 'M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zM124 296c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h264c6.6 0 12 5.4 12 12v56c0 6.6-5.4 12-12 12H124z';
MinusCircle.SHAPE = new Shape( MinusCircle.PATH_DATA );

export default MinusCircle;