// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Moon extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Moon.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Moon.PATH_DATA = 'M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z';
Moon.SHAPE = new Shape( Moon.PATH_DATA );

export default Moon;