// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Paragraph extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Paragraph.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Paragraph.PATH_DATA = 'M448 48v32a16 16 0 0 1-16 16h-48v368a16 16 0 0 1-16 16h-32a16 16 0 0 1-16-16V96h-32v368a16 16 0 0 1-16 16h-32a16 16 0 0 1-16-16V352h-32a160 160 0 0 1 0-320h240a16 16 0 0 1 16 16z';
Paragraph.SHAPE = new Shape( Paragraph.PATH_DATA );

export default Paragraph;