// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class PlayCircle extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( PlayCircle.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
PlayCircle.PATH_DATA = 'M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm115.7 272l-176 101c-15.8 8.8-35.7-2.5-35.7-21V152c0-18.4 19.8-29.8 35.7-21l176 107c16.4 9.2 16.4 32.9 0 42z';
PlayCircle.SHAPE = new Shape( PlayCircle.PATH_DATA );

export default PlayCircle;