// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Play extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Play.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Play.PATH_DATA = 'M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z';
Play.SHAPE = new Shape( Play.PATH_DATA );

export default Play;