// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Qrcode extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Qrcode.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Qrcode.PATH_DATA = 'M0 224h192V32H0v192zM64 96h64v64H64V96zm192-64v192h192V32H256zm128 128h-64V96h64v64zM0 480h192V288H0v192zm64-128h64v64H64v-64zm352-64h32v128h-96v-32h-32v96h-64V288h96v32h64v-32zm0 160h32v32h-32v-32zm-64 0h32v32h-32v-32z';
Qrcode.SHAPE = new Shape( Qrcode.PATH_DATA );

export default Qrcode;