// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class SdCard extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( SdCard.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
SdCard.PATH_DATA = 'M320 0H128L0 128v320c0 35.3 28.7 64 64 64h256c35.3 0 64-28.7 64-64V64c0-35.3-28.7-64-64-64zM160 160h-48V64h48v96zm80 0h-48V64h48v96zm80 0h-48V64h48v96z';
SdCard.SHAPE = new Shape( SdCard.PATH_DATA );

export default SdCard;