// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class SortUp extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( SortUp.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
SortUp.PATH_DATA = 'M279 224H41c-21.4 0-32.1-25.9-17-41L143 64c9.4-9.4 24.6-9.4 33.9 0l119 119c15.2 15.1 4.5 41-16.9 41z';
SortUp.SHAPE = new Shape( SortUp.PATH_DATA );

export default SortUp;