// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class SquareFull extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( SquareFull.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
SquareFull.PATH_DATA = 'M512 512H0V0h512v512z';
SquareFull.SHAPE = new Shape( SquareFull.PATH_DATA );

export default SquareFull;