// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class StarHalf extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( StarHalf.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
StarHalf.PATH_DATA = 'M288 0c-11.4 0-22.8 5.9-28.7 17.8L194 150.2 47.9 171.4c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.1 23 46 46.4 33.7L288 439.6V0z';
StarHalf.SHAPE = new Shape( StarHalf.PATH_DATA );

export default StarHalf;