// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class StickyNote extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( StickyNote.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
StickyNote.PATH_DATA = 'M312 320h136V56c0-13.3-10.7-24-24-24H24C10.7 32 0 42.7 0 56v400c0 13.3 10.7 24 24 24h264V344c0-13.2 10.8-24 24-24zm129 55l-98 98c-4.5 4.5-10.6 7-17 7h-6V352h128v6.1c0 6.3-2.5 12.4-7 16.9z';
StickyNote.SHAPE = new Shape( StickyNote.PATH_DATA );

export default StickyNote;