// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Stop extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Stop.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Stop.PATH_DATA = 'M400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48z';
Stop.SHAPE = new Shape( Stop.PATH_DATA );

export default Stop;