// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class StopCircle extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( StopCircle.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
StopCircle.PATH_DATA = 'M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm96 328c0 8.8-7.2 16-16 16H176c-8.8 0-16-7.2-16-16V176c0-8.8 7.2-16 16-16h160c8.8 0 16 7.2 16 16v160z';
StopCircle.SHAPE = new Shape( StopCircle.PATH_DATA );

export default StopCircle;