// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Tablet extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Tablet.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Tablet.PATH_DATA = 'M400 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM224 480c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32z';
Tablet.SHAPE = new Shape( Tablet.PATH_DATA );

export default Tablet;