// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Voicemail extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Voicemail.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Voicemail.PATH_DATA = 'M496 128a144 144 0 0 0-119.74 224H263.74A144 144 0 1 0 144 416h352a144 144 0 0 0 0-288zM64 272a80 80 0 1 1 80 80 80 80 0 0 1-80-80zm432 80a80 80 0 1 1 80-80 80 80 0 0 1-80 80z';
Voicemail.SHAPE = new Shape( Voicemail.PATH_DATA );

export default Voicemail;