// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class VolumeOff extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( VolumeOff.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
VolumeOff.PATH_DATA = 'M215 71l-89 89H24a24 24 0 0 0-24 24v144a24 24 0 0 0 24 24h102.06L215 441c15 15 41 4.47 41-17V88c0-21.47-26-32-41-17z';
VolumeOff.SHAPE = new Shape( VolumeOff.PATH_DATA );

export default VolumeOff;