// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class WindowMinimize extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( WindowMinimize.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
WindowMinimize.PATH_DATA = 'M464 352H48c-26.5 0-48 21.5-48 48v32c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48v-32c0-26.5-21.5-48-48-48z';
WindowMinimize.SHAPE = new Shape( WindowMinimize.PATH_DATA );

export default WindowMinimize;