// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class WindowMaximize extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( WindowMaximize.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
WindowMaximize.PATH_DATA = 'M464 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm-16 160H64v-84c0-6.6 5.4-12 12-12h360c6.6 0 12 5.4 12 12v84z';
WindowMaximize.SHAPE = new Shape( WindowMaximize.PATH_DATA );

export default WindowMaximize;