// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Bandcamp extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Bandcamp.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Bandcamp.PATH_DATA = 'M256,8C119,8,8,119,8,256S119,504,256,504,504,393,504,256,393,8,256,8Zm48.2,326.1h-181L207.9,178h181Z';
Bandcamp.SHAPE = new Shape( Bandcamp.PATH_DATA );

export default Bandcamp;