// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class BlackTie extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( BlackTie.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
BlackTie.PATH_DATA = 'M0 32v448h448V32H0zm316.5 325.2L224 445.9l-92.5-88.7 64.5-184-64.5-86.6h184.9L252 173.2l64.5 184z';
BlackTie.SHAPE = new Shape( BlackTie.PATH_DATA );

export default BlackTie;