// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Buysellads extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Buysellads.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Buysellads.PATH_DATA = 'M224 150.7l42.9 160.7h-85.8L224 150.7zM448 80v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V80c0-26.5 21.5-48 48-48h352c26.5 0 48 21.5 48 48zm-65.3 325.3l-94.5-298.7H159.8L65.3 405.3H156l111.7-91.6 24.2 91.6h90.8z';
Buysellads.SHAPE = new Shape( Buysellads.PATH_DATA );

export default Buysellads;