// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Cloudsmith extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Cloudsmith.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Cloudsmith.PATH_DATA = 'M332.5 419.9c0 46.4-37.6 84.1-84 84.1s-84-37.7-84-84.1 37.6-84 84-84 84 37.6 84 84zm-84-243.9c46.4 0 80-37.6 80-84s-33.6-84-80-84-88 37.6-88 84-29.6 76-76 76-84 41.6-84 88 37.6 80 84 80 84-33.6 84-80 33.6-80 80-80z';
Cloudsmith.SHAPE = new Shape( Cloudsmith.PATH_DATA );

export default Cloudsmith;