// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Css3 extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Css3.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Css3.PATH_DATA = 'M480 32l-64 368-223.3 80L0 400l19.6-94.8h82l-8 40.6L210 390.2l134.1-44.4 18.8-97.1H29.5l16-82h333.7l10.5-52.7H56.3l16.3-82H480z';
Css3.SHAPE = new Shape( Css3.PATH_DATA );

export default Css3;