// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Deviantart extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Deviantart.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Deviantart.PATH_DATA = 'M320 93.2l-98.2 179.1 7.4 9.5H320v127.7H159.1l-13.5 9.2-43.7 84c-.3 0-8.6 8.6-9.2 9.2H0v-93.2l93.2-179.4-7.4-9.2H0V102.5h156l13.5-9.2 43.7-84c.3 0 8.6-8.6 9.2-9.2H320v93.1z';
Deviantart.SHAPE = new Shape( Deviantart.PATH_DATA );

export default Deviantart;