// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Ethereum extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Ethereum.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Ethereum.PATH_DATA = 'M311.9 260.8L160 353.6 8 260.8 160 0l151.9 260.8zM160 383.4L8 290.6 160 512l152-221.4-152 92.8z';
Ethereum.SHAPE = new Shape( Ethereum.PATH_DATA );

export default Ethereum;