// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class FacebookF extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( FacebookF.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
FacebookF.PATH_DATA = 'M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z';
FacebookF.SHAPE = new Shape( FacebookF.PATH_DATA );

export default FacebookF;