// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Flipboard extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Flipboard.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Flipboard.PATH_DATA = 'M0 32v448h448V32H0zm358.4 179.2h-89.6v89.6h-89.6v89.6H89.6V121.6h268.8v89.6z';
Flipboard.SHAPE = new Shape( Flipboard.PATH_DATA );

export default Flipboard;