// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../../kite/js/imports.js';
import fortAwesomeString from './fortAwesomeString.js';

export default new Shape( fortAwesomeString ).makeImmutable();