// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class HackerNews extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( HackerNews.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
HackerNews.PATH_DATA = 'M0 32v448h448V32H0zm21.2 197.2H21c.1-.1.2-.3.3-.4 0 .1 0 .3-.1.4zm218 53.9V384h-31.4V281.3L128 128h37.3c52.5 98.3 49.2 101.2 59.3 125.6 12.3-27 5.8-24.4 60.6-125.6H320l-80.8 155.1z';
HackerNews.SHAPE = new Shape( HackerNews.PATH_DATA );

export default HackerNews;