// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Instalod extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Instalod.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Instalod.PATH_DATA = 'M153.384,480H387.113L502.554,275.765,204.229,333.211ZM504.726,240.078,387.113,32H155.669L360.23,267.9ZM124.386,48.809,7.274,256,123.236,461.154,225.627,165.561Z';
Instalod.SHAPE = new Shape( Instalod.PATH_DATA );

export default Instalod;