// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../../kite/js/imports.js';
import linkedinString from './linkedinString.js';

export default new Shape( linkedinString ).makeImmutable();