// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../../kite/js/imports.js';
import lyftString from './lyftString.js';

export default new Shape( lyftString ).makeImmutable();