// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Mix extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Mix.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Mix.PATH_DATA = 'M0 64v348.9c0 56.2 88 58.1 88 0V174.3c7.9-52.9 88-50.4 88 6.5v175.3c0 57.9 96 58 96 0V240c5.3-54.7 88-52.5 88 4.3v23.8c0 59.9 88 56.6 88 0V64H0z';
Mix.SHAPE = new Shape( Mix.PATH_DATA );

export default Mix;