// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Modx extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Modx.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Modx.PATH_DATA = 'M356 241.8l36.7 23.7V480l-133-83.8L356 241.8zM440 75H226.3l-23 37.8 153.5 96.5L440 75zm-89 142.8L55.2 32v214.5l46 29L351 217.8zM97 294.2L8 437h213.7l125-200.5L97 294.2z';
Modx.SHAPE = new Shape( Modx.PATH_DATA );

export default Modx;