// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Patreon extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Patreon.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Patreon.PATH_DATA = 'M512 194.8c0 101.3-82.4 183.8-183.8 183.8-101.7 0-184.4-82.4-184.4-183.8 0-101.6 82.7-184.3 184.4-184.3C429.6 10.5 512 93.2 512 194.8zM0 501.5h90v-491H0v491z';
Patreon.SHAPE = new Shape( Patreon.PATH_DATA );

export default Patreon;