// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Servicestack extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Servicestack.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Servicestack.PATH_DATA = 'M88 216c81.7 10.2 273.7 102.3 304 232H0c99.5-8.1 184.5-137 88-232zm32-152c32.3 35.6 47.7 83.9 46.4 133.6C249.3 231.3 373.7 321.3 400 448h96C455.3 231.9 222.8 79.5 120 64z';
Servicestack.SHAPE = new Shape( Servicestack.PATH_DATA );

export default Servicestack;