// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class ThinkPeaks extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( ThinkPeaks.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
ThinkPeaks.PATH_DATA = 'M465.4 409.4l87.1-150.2-32-.3-55.1 95L259.2 0 23 407.4l32 .3L259.2 55.6zm-355.3-44.1h32.1l117.4-202.5L463 511.9l32.5.1-235.8-404.6z';
ThinkPeaks.SHAPE = new Shape( ThinkPeaks.PATH_DATA );

export default ThinkPeaks;