// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../../../kite/js/imports.js';
import uikitString from './uikitString.js';

export default new Shape( uikitString ).makeImmutable();