// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Uikit extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Uikit.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Uikit.PATH_DATA = 'M443.9 128v256L218 512 0 384V169.7l87.6 45.1v117l133.5 75.5 135.8-75.5v-151l-101.1-57.6 87.6-53.1L443.9 128zM308.6 49.1L223.8 0l-88.6 54.8 86 47.3 87.4-53z';
Uikit.SHAPE = new Shape( Uikit.PATH_DATA );

export default Uikit;