// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Unsplash extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Unsplash.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Unsplash.PATH_DATA = 'M448,230.17V480H0V230.17H141.13V355.09H306.87V230.17ZM306.87,32H141.13V156.91H306.87Z';
Unsplash.SHAPE = new Shape( Unsplash.PATH_DATA );

export default Unsplash;