// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Viacoin extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Viacoin.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Viacoin.PATH_DATA = 'M384 32h-64l-80.7 192h-94.5L64 32H0l48 112H0v48h68.5l13.8 32H0v48h102.8L192 480l89.2-208H384v-48h-82.3l13.8-32H384v-48h-48l48-112zM192 336l-27-64h54l-27 64z';
Viacoin.SHAPE = new Shape( Viacoin.PATH_DATA );

export default Viacoin;