// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Vuejs extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Vuejs.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Vuejs.PATH_DATA = 'M356.9 64.3H280l-56 88.6-48-88.6H0L224 448 448 64.3h-91.1zm-301.2 32h53.8L224 294.5 338.4 96.3h53.8L224 384.5 55.7 96.3z';
Vuejs.SHAPE = new Shape( Vuejs.PATH_DATA );

export default Vuejs;