// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import FANode from '../FANode.js';
import Shape from '../../../../kite/js/Shape.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class Yahoo extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( Yahoo.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
Yahoo.PATH_DATA = 'M223.69,141.06,167,284.23,111,141.06H14.93L120.76,390.19,82.19,480h94.17L317.27,141.06Zm105.4,135.79a58.22,58.22,0,1,0,58.22,58.22A58.22,58.22,0,0,0,329.09,276.85ZM394.65,32l-93,223.47H406.44L499.07,32Z';
Yahoo.SHAPE = new Shape( Yahoo.PATH_DATA );

export default Yahoo;