// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class YandexInternational extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( YandexInternational.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
YandexInternational.PATH_DATA = 'M129.5 512V345.9L18.5 48h55.8l81.8 229.7L250.2 0h51.3L180.8 347.8V512h-51.3z';
YandexInternational.SHAPE = new Shape( YandexInternational.PATH_DATA );

export default YandexInternational;