// Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

import Shape from '../../../../kite/js/Shape.js';
import FANode from '../FANode.js';

/**
 * Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.
 */
class YCombinator extends FANode {

  /**
   * @param {Object} [options}
   */
  constructor( options ) {
    super( YCombinator.SHAPE, options );
  }
}

// Export the raw path data in case more complex usage is necessary
YCombinator.PATH_DATA = 'M448 32v448H0V32h448zM236 287.5L313.5 142h-32.7L235 233c-4.7 9.3-9 18.3-12.8 26.8L210 233l-45.2-91h-35l76.7 143.8v94.5H236v-92.8z';
YCombinator.SHAPE = new Shape( YCombinator.PATH_DATA );

export default YCombinator;